name: 052-docker-ghcr-workflow

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: livewallpaper3dparallax/github-actions-course
  IMAGE_TAG: 1.0.${{ github.run_number }}

jobs:
  build-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install the cosign tool
      - name: Install cosign
        run: |
          curl -sSLo /usr/local/bin/cosign https://github.com/sigstore/cosign/releases/download/v1.4.0/cosign-linux-amd64
          chmod +x /usr/local/bin/cosign

      # Setup Docker buildx
      - name: Setup Docker buildx
        run: |
          docker buildx create --use

      # Login to Docker registry
      - name: Log into registry ${{ env.REGISTRY }}
        run: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}

      # Build and push Docker image with Buildx
      - name: Build and push Docker image
        run: |
          docker buildx build \
            --file 03-app-dotnet/Dockerfile \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            --push .

      # Sign the resulting Docker image digest
      - name: Sign the published Docker image
        run: |
          cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

